### PR TITLE
upgrade 1.19

### PR DESCRIPTION
**Pull request by hawkingrei**
upgrade to go1.19 and update all dependencies.

Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>

### CODE REVIEW

**Comment by hawkingrei** [comment]
BTW, I and @YangKeao try to add bazel to mysql-test. but we find it has difficult version dependencies between mysql-tester and mysql. I hope we can move it into tidb repo.

**Comment by hawkingrei** [comment]
@dveeden PTAL

**Comment by YangKeao** [comment]
> I hope we can move it into tidb repo.

I'm actually not sure whether it will bring benefit for executing mysql-test with bazel. Because the problem we faced is importing the tidb repo (but not this repo) and detect whether it has changed.

For mysql-tester, the problem can be solved through importing it directly: https://github.com/pingcap/tidb-test/blob/6a94e3aabf881ba7eb2704575ff1e2ca69908bc3/mysql_test/tools.go

**Comment by hawkingrei** [comment]
> > I hope we can move it into tidb repo.
> 
> I'm actually not sure whether it will bring benefit for executing mysql-test with bazel. Because the problem we faced is importing the tidb repo (but not this repo) and detect whether it has changed.
> 
> For mysql-tester, the problem can be solved through importing it directly: https://github.com/pingcap/tidb-test/blob/6a94e3aabf881ba7eb2704575ff1e2ca69908bc3/mysql_test/tools.go

Let me make a demo to show this.

**Review by dveeden — APPROVED** [review]

**Pull request closed without merging**
