### PR TITLE
CI: Setup GitHub actions

### PR DESCRIPTION
**Pull request by dveeden**
Maybe we can do some testing in CI with GitHub actions?

### CODE REVIEW

**Comment by dveeden** [comment]
Note that `Makefile` has a `#` before `./mysql-tester -check-error` so we only run the tests but without an actual TiDB instance. Maybe we can use [TiDB Action](https://github.com/Icemap/tidb-action) from @Icemap for this. This can be done as part of this PR or later.

**Review by mjonss — APPROVED** [review]

**Comment by dveeden** [comment]
Another thing we *could* do after this has been merged is to run `golangci-lint`. See also #121

**Review by Defined2014 — APPROVED** [review]

**Comment by Defined2014** [comment]
@bb7133  PTAL

**Review by bb7133 — APPROVED** [review]
LGTM

**Pull request merged**
